# Generated by Django 3.2.8 on 2021-10-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('kind_name', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('today_price', models.CharField(max_length=30)),
                ('average_price', models.CharField(max_length=30)),
            ],
        ),
    ]
