# Generated by Django 3.2.8 on 2021-10-22 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_api_table_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
