# Generated by Django 3.2.8 on 2021-10-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_table',
            fields=[
                ('primary_key', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(null=True, upload_to='')),
                ('image3', models.FileField(null=True, upload_to='')),
                ('content', models.TextField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.PositiveSmallIntegerField(choices=[(0, '소분'), (1, '나눔'), (2, '완료')])),
            ],
        ),
    ]
