# Generated by Django 3.2.8 on 2021-10-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_table',
            old_name='primary_key',
            new_name='id',
        ),
    ]
