# Generated by Django 3.2.8 on 2021-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0002_rename_primary_key_post_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_table',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_table',
            name='user_key',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
