# Generated by Django 3.2.8 on 2021-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0003_auto_20211008_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_key', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('user_key', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('local', models.PositiveIntegerField()),
            ],
        ),
    ]
